config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins, :skip => [:registerable], path: 'admins', controllers: { sessions: "admins/sessions" } do
  #   resources :products, only: [:create]
  #   resources :users
  # end
  # authenticated :admin do
  #   root  to: 'pages#home'
  # end
  # resources :products, only: [:show, :update, :index]
  # devise_for :users, :controllers => { :invitable => 'users/invitations'}


  root to: 'pages#home'

  get 'support', to: 'pages#support', as: :support
  get 'about', to: 'pages#about', as: :about
  get 'soon', to: 'pages#soon', as: :soon

  resources :contacts, only: [:new, :create, :index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo1.png"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "About", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Contact", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "About", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Contact", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo1.png"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "About", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Products", products_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Support", support_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Contact", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%#= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% elsif admin_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "admin.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%#= link_to t(".sign_in", default: "Distributor Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn btn-distributor" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">About</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Support</a></li>
      </ul>
    </div>
  </div>
</div>