config/routes.rb
Rails.application.routes.draw do

  # devise_for :admins, :skip => [:registerable], path: 'admins', controllers: { sessions: "admins/sessions" } do
  #   resources :products, only: [:create]
  #   resources :users
  # end
  # authenticated :admin do
  #   root  to: 'pages#home'
  # end
  # resources :products, only: [:show, :update, :index]
  # devise_for :users, :controllers => { :invitable => 'users/invitations'}


  root to: 'pages#home'

  get 'support', to: 'pages#support', as: :support
  get 'about', to: 'pages#about', as: :about
  get 'soon', to: 'pages#soon', as: :soon

  resources :contacts, only: [:new, :create, :index]

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true, length: { minimum: 2 }
  attribute :phone, :validate => /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/,
                               message: I18n.t('global.errors.phone_format')
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true


  def headers
    {
      :subject => "Contact Form - #{name}",
      :to => "contact@galenvs.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :create, :new]

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      redirect_to contacts_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/views/contacts/index.html.erb
<div class="section">
  <div class="top-border left"></div>
  <div class="top-border right"></div>
  <h1>CONTACT US</h1>
  <p class="contact-us-content" style="color:black; font-size: 18px;">At <strong style="color: #761f4a;">Galenvs</strong> we are commited to providing the life sciences R&D community with tools that address complex biomedical challenges through simple and elegant solutions. <br><br>
  We would love to hear from you!
  Let us know how we can help by filling one of the following contact forms.</p>
  <div>
    <!-- <a href="">General Inquiry</a> -->
    <div class="custom-button"><%= link_to "General Inquiry", new_contact_path %></div>
  </div>
  <!-- <div> -->
    <!-- <a href="#">Become a distributor</a> -->
  <!-- <div class="custom-button" style="color:white;"><%#= link_to "Become a distributor", new_contact_path %></div>
  </div> -->
</div>


<div class="section">
  <div class="top-border left"> </div>
  <div class="top-border right"></div>
  <h2>Our Location</h2>

  <h5>6830 Parc Ave, <strong style="color: #761f4a;">Suite 513</strong>, Montreal Quebec, H3N 1W7 </h5>
  <iframe width="90%" height="450" frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDDIQ6UxR0-PH8FoN9ltcZ4DMBtY_8JMt4
    &q=6830+Park+Ave,+Montreal,+QC+H3N+1W7" allowfullscreen>
  </iframe>
</div>

app/views/contacts/new.html.erb
<!--
<div class="border-form-div">
  <%#= simple_form_for (@contact )do |f| %>
      <%# if flash[:error].present? %>
      <p> flash[:error]</p>
      <%# end %>
      <%#= f.label :name %> <br>
      <%#= f.text_field :name, required: true, placeholder: 'Firstname Lastname' %>

      <br>
      <%#= f.label :email %> <br>
      <%#= f.text_field :email, required: true, placeholder: 'example@email.com' %>

      <br>
      <%#= f.label :message %> <br>
      <%#= f.text_area :message, as: :text, width: :auto, placeholder: 'Your message' %>


      <%#= f.label :nickname, hidden: true %> <br>
      <%#= f.text_field :nickname, hidden: true, hint: 'leave this field blank'%>


      <%#= f.submit 'Send Message', class: "button", wrapper_html: { class: 'btn btn-success' } %>
    <%# end %>
</div>
 -->


<div class="border-form-div">
  <div class="panel">
    <div class="panel-heading">
      Contact Us
    </div>
    <div class="panel-body">
      <%= simple_form_for (@contact )do |f| %>
      <% if flash[:error].present? %>
      <p> flash[:error]</p>
      <% end %>

      <%= f.input :name, required: true, placeholder: 'FirstName LastName' %>

      <br>
      <%= f.input :email, required: true, placeholder: 'example@email.com' %>

      <br>
      <%= f.input :phone, required:true, placeholder: '514-111-2233' %>


      <br>
      <%= f.input :message, as: :text, width: :auto, placeholder: 'Your message' %>


      <%= f.label :nickname, hidden: true %> <br>
      <%= f.text_field :nickname, hidden: true, hint: 'leave this field blank'%>


      <%= f.submit 'Send Message', class: "button", wrapper_html: { class: 'btn btn-success' } %>
    <% end %>
    </div>
  </div>
</div>